name: First WorkFlow
on: workflow_dispatch
jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - name: First Step
        run: |
          echo "First Github Actions"
          echo "Second Github Actions"
