name: First WorkFlow
on: 
  workflow_dispatch:
    inputs:
      environment:
        description: Choose the environment to deploy
        required: true
        type: choice
        options:
          - DEV
          - QA
          - PROD
jobs:
  Build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{steps.step1.outputs.version}}
    steps:
      - name: First Step
        if: "${{inputs.environment == 'PROD'}}"
        id: step1
        run: |
          echo "First Github Actions ${{inputs.environment}}"
          echo "version=0.0.1" >> $GITHUB.OUTPUT
  Test: 
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Second step
        run: echo "${{needs.Build.outputs.version}}"
