name: First WorkFlow
on: 
  workflow_dispatch:
    inputs:
      environment:
        description: Choose the environment to deploy
        required: true
        type: choice
        options:
          - DEV
          - QA
          - PROD
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: First Step
        run: echo "First Github Actions ${{inputs.environment}}"
  Test: 
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Second step
        run: echo "${{github.actor}}
